// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xMDtcv-DcNvqQ85QudpjyCiNxDhjlqk',
    appId: '1:1070441052675:web:951e70b98cd8fef58b6c36',
    messagingSenderId: '1070441052675',
    projectId: 'fir-auth-app-a32da',
    authDomain: 'fir-auth-app-a32da.firebaseapp.com',
    storageBucket: 'fir-auth-app-a32da.firebasestorage.app',
    measurementId: 'G-6L94D08CZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcnvHV0c8yPYpJg-Oim3Eo57FXc7oKP-8',
    appId: '1:1070441052675:android:5d83df5903fc553c8b6c36',
    messagingSenderId: '1070441052675',
    projectId: 'fir-auth-app-a32da',
    storageBucket: 'fir-auth-app-a32da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVroHzf4uOEgq23sGCCSKHGu_--mQSyR0',
    appId: '1:1070441052675:ios:d4006d3c856640678b6c36',
    messagingSenderId: '1070441052675',
    projectId: 'fir-auth-app-a32da',
    storageBucket: 'fir-auth-app-a32da.firebasestorage.app',
    iosBundleId: 'com.rsharma.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVroHzf4uOEgq23sGCCSKHGu_--mQSyR0',
    appId: '1:1070441052675:ios:d4006d3c856640678b6c36',
    messagingSenderId: '1070441052675',
    projectId: 'fir-auth-app-a32da',
    storageBucket: 'fir-auth-app-a32da.firebasestorage.app',
    iosBundleId: 'com.rsharma.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xMDtcv-DcNvqQ85QudpjyCiNxDhjlqk',
    appId: '1:1070441052675:web:500ae67c052c3e098b6c36',
    messagingSenderId: '1070441052675',
    projectId: 'fir-auth-app-a32da',
    authDomain: 'fir-auth-app-a32da.firebaseapp.com',
    storageBucket: 'fir-auth-app-a32da.firebasestorage.app',
    measurementId: 'G-JWC01MZLP3',
  );
}